package main

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/wesnick/gwcli/pkg/gwcli"
	"github.com/wesnick/gwcli/pkg/gwcli/gmailctl"
)

const downloadHeader = `// Auto-generated by gwcli gmailctl download
// Edit as needed, then use 'gwcli gmailctl apply' to push changes.
`

// runGmailctlDownload downloads filters from Gmail to config.jsonnet
func runGmailctlDownload(ctx context.Context, configDir, userEmail, outputFile string, out *outputWriter) error {
	// Get config paths
	paths, err := gwcli.GetConfigPaths(configDir)
	if err != nil {
		return err
	}

	// Initialize Gmail service with gwcli's auth (supports service accounts)
	svc, err := gwcli.InitializeAuth(ctx, paths, userEmail)
	if err != nil {
		return fmt.Errorf("connecting to Gmail: %w", err)
	}

	// Create API wrapper
	api := gmailctl.NewGmailAPI(ctx, svc, "me")

	// Fetch current Gmail state
	if out.verbose {
		fmt.Fprintln(os.Stderr, "Fetching filters from Gmail...")
	}
	filters, err := api.ListFilters()
	if err != nil {
		return fmt.Errorf("fetching filters: %w", err)
	}

	if out.verbose {
		fmt.Fprintln(os.Stderr, "Fetching labels from Gmail...")
	}
	labels, err := api.ListLabels()
	if err != nil {
		return fmt.Errorf("fetching labels: %w", err)
	}

	if out.verbose {
		fmt.Fprintf(os.Stderr, "Found %d filters and %d labels\n", len(filters), len(labels))
	}

	// Convert to config
	cfg, err := gmailctl.ReverseImport(filters, labels)
	if err != nil {
		return fmt.Errorf("importing config: %w", err)
	}

	// Write jsonnet
	var output *os.File
	if outputFile != "" && outputFile != "-" {
		output, err = os.Create(outputFile)
		if err != nil {
			return fmt.Errorf("creating output file: %w", err)
		}
		defer output.Close()
	} else {
		output = os.Stdout
	}

	if err := gmailctl.MarshalJsonnet(cfg, output, downloadHeader); err != nil {
		return fmt.Errorf("writing jsonnet: %w", err)
	}

	if outputFile != "" && outputFile != "-" {
		fmt.Fprintf(os.Stderr, "Config downloaded to: %s\n", outputFile)
	}

	return nil
}

// runGmailctlApply applies config.jsonnet to Gmail filters
func runGmailctlApply(ctx context.Context, configDir, userEmail string, skipConfirm, removeLabels bool, out *outputWriter) error {
	// Get config paths
	paths, err := gwcli.GetConfigPaths(configDir)
	if err != nil {
		return err
	}

	// Load local config
	if out.verbose {
		fmt.Fprintf(os.Stderr, "Reading config from: %s\n", paths.Config)
	}
	localCfg, err := gmailctl.ReadFile(paths.Config, "")
	if err != nil {
		if err == gmailctl.ErrNotFound {
			return fmt.Errorf("config.jsonnet not found at %s: run 'gwcli gmailctl download' first or create the file manually", paths.Config)
		}
		return fmt.Errorf("reading config: %w", err)
	}

	// Parse config to Gmail format
	parsed, err := gmailctl.FromConfig(localCfg)
	if err != nil {
		return fmt.Errorf("parsing config: %w", err)
	}

	// Initialize Gmail service
	svc, err := gwcli.InitializeAuth(ctx, paths, userEmail)
	if err != nil {
		return fmt.Errorf("connecting to Gmail: %w", err)
	}

	api := gmailctl.NewGmailAPI(ctx, svc, "me")

	// Fetch upstream state
	if out.verbose {
		fmt.Fprintln(os.Stderr, "Fetching current Gmail state...")
	}
	upstream, err := gmailctl.FromAPI(api)
	if err != nil {
		return fmt.Errorf("fetching Gmail state: %w", err)
	}

	// Compute diff
	diff, err := gmailctl.Diff(parsed.GmailConfig, upstream, false, gmailctl.DefaultContextLines, !out.noColor)
	if err != nil {
		return fmt.Errorf("computing diff: %w", err)
	}

	if diff.Empty() {
		fmt.Println("No changes to apply.")
		return nil
	}

	// Validate diff
	if err := diff.Validate(); err != nil {
		return fmt.Errorf("invalid changes: %w", err)
	}

	// Show diff
	fmt.Printf("Changes to apply:\n\n%s\n", diff)

	// Confirm
	if !skipConfirm {
		fmt.Print("Apply these changes? [y/N] ")
		reader := bufio.NewReader(os.Stdin)
		response, _ := reader.ReadString('\n')
		response = strings.TrimSpace(strings.ToLower(response))
		if response != "y" && response != "yes" {
			fmt.Println("Aborted.")
			return nil
		}
	}

	// Apply
	fmt.Println("Applying changes...")
	if err := gmailctl.Apply(diff, api, removeLabels); err != nil {
		return fmt.Errorf("applying changes: %w", err)
	}

	fmt.Println("Done.")
	return nil
}

// runGmailctlDiff shows diff between local config and Gmail
func runGmailctlDiff(ctx context.Context, configDir, userEmail string, out *outputWriter) error {
	// Get config paths
	paths, err := gwcli.GetConfigPaths(configDir)
	if err != nil {
		return err
	}

	// Load local config
	if out.verbose {
		fmt.Fprintf(os.Stderr, "Reading config from: %s\n", paths.Config)
	}
	localCfg, err := gmailctl.ReadFile(paths.Config, "")
	if err != nil {
		if err == gmailctl.ErrNotFound {
			return fmt.Errorf("config.jsonnet not found at %s: run 'gwcli gmailctl download' first or create the file manually", paths.Config)
		}
		return fmt.Errorf("reading config: %w", err)
	}

	// Parse config to Gmail format
	parsed, err := gmailctl.FromConfig(localCfg)
	if err != nil {
		return fmt.Errorf("parsing config: %w", err)
	}

	// Initialize Gmail service
	svc, err := gwcli.InitializeAuth(ctx, paths, userEmail)
	if err != nil {
		return fmt.Errorf("connecting to Gmail: %w", err)
	}

	api := gmailctl.NewGmailAPI(ctx, svc, "me")

	// Fetch upstream state
	if out.verbose {
		fmt.Fprintln(os.Stderr, "Fetching current Gmail state...")
	}
	upstream, err := gmailctl.FromAPI(api)
	if err != nil {
		return fmt.Errorf("fetching Gmail state: %w", err)
	}

	// Compute diff
	diff, err := gmailctl.Diff(parsed.GmailConfig, upstream, false, gmailctl.DefaultContextLines, !out.noColor)
	if err != nil {
		return fmt.Errorf("computing diff: %w", err)
	}

	if diff.Empty() {
		fmt.Println("No differences.")
		return nil
	}

	fmt.Print(diff)
	return nil
}
